defaults: &defaults
  adapter: mysql2
  database: try_rails4
  pool: 5
  timeout: 5000
  username: root
  password: 
  host: localhost
  port: 3306

production:
  <<: *defaults

development:
  <<: *defaults
  database: try_rails4_development

test:
  <<: *defaults
  database: try_rails4_test
